# Documentation on libs.versions.toml: https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.1.0"
kore = "1.24.0-1.21.4"

[libraries]
kore = { module = "io.github.ayfri.kore:kore", version.ref = "kore" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
